### ISSUE TITLE
Add documentation for plugins (k8/couchdb)

### ISSUE THREAD

**Issue by honeydbio** [foospidy/honeydb-agent-docs#1]

**Comment by PeterHayman** [comment]
![Image](https://github.com/user-attachments/assets/e4964a17-9d4e-4cca-bb5a-d6559b2e1878)

**Comment by PeterHayman** [comment]
and under events:
![Image](https://github.com/user-attachments/assets/6f455f3a-2a73-4344-a1ba-c231d966d369)
